/**
 * Track My Chambers - Public Client Case Access Portal Module
 * Displays case progress, court forums, stages, and hearing history
 * for clients accessing via direct link (/portal?token=...).
 * FINANCIAL DATA IS COMPLETELY OMITTED FOR CONFIDENTIALITY.
 */

import api from './api.js';
import db from './db.js';

const portalModule = {
  init() {
    console.log("PortalModule: Initializing Public Client Access Portal...");
  },

  async render(tokenFromUrl) {
    const container = document.getElementById('portal-page-content');
    if (!container) return;

    // Extract token from URL search parameter if not passed
    const urlParams = new URLSearchParams(window.location.search);
    const token = tokenFromUrl || urlParams.get('token') || urlParams.get('client') || '';

    if (!token) {
      this.renderError(container, "Missing Client Access Token", "Please use the direct link provided by your advocate's chamber.");
      return;
    }

    container.innerHTML = `
      <div style="text-align:center; padding:3rem;" class="text-muted">
        <div class="spinner" style="margin: 0 auto 1rem auto;"></div>
        <p>Loading your case progress portal...</p>
      </div>
    `;

    try {
      const data = await api.portal.get(token);
      this.renderPortal(container, data);
    } catch (err) {
      console.warn("Server portal API unavailable, attempting local cache fallback:", err);
      const fallbackData = this.calculateLocalPortal(token);
      if (fallbackData) {
        this.renderPortal(container, fallbackData);
      } else {
        this.renderError(container, "Invalid or Expired Link", "This case access link is invalid or has been regenerated by the chamber. Please contact your advocate for an updated link.");
      }
    }
  },

  calculateLocalPortal(token) {
    const clients = db.getClients() || [];
    const client = clients.find(c => (c.accessToken && c.accessToken === token) || (c.id && String(c.id) === String(token)));
    if (!client) return null;

    const allCases = db.getCases() || [];
    const cases = allCases.filter(cs => {
      if (!cs) return false;
      const csClientId = (cs.clientId || cs.client_id || '').toString();
      const cId = (client.id || '').toString();

      if (csClientId && cId && csClientId === cId) return true;
      if (cs.clientName && client.name && cs.clientName.toLowerCase().trim() === client.name.toLowerCase().trim()) return true;
      if (cs.client && client.name && String(cs.client).toLowerCase().trim() === client.name.toLowerCase().trim()) return true;
      return false;
    });

    const settings = db.getSettings() || {};

    return {
      client: {
        id: client.id,
        name: client.name,
        type: client.type || 'Individual',
        accessToken: client.accessToken || token
      },
      chambers: {
        lawyerName: settings.lawyerName || 'Adv. Vaibhav Sharma',
        firmName: settings.firmName || 'VSH Legal Chambers'
      },
      cases: cases.map(cs => ({
        id: cs.id,
        caseNumber: cs.caseNumber || cs.cnrNumber || 'N/A',
        title: cs.title || cs.caseTitle || 'Legal Matter',
        court: cs.court || cs.forum || 'Court Forum',
        caseType: cs.caseType || cs.type || 'General',
        status: cs.status || 'Active',
        stage: cs.stage || 'In Progress',
        nextHearingDate: cs.nextHearingDate || cs.nextDate || null,
        hearings: cs.hearings || []
      }))
    };
  },

  renderError(container, title, message) {
    container.innerHTML = `
      <div class="card" style="max-width: 600px; margin: 3rem auto; padding: 2rem; text-align: center; border-top: 4px solid var(--color-danger);">
        <div style="width: 56px; height: 56px; background: rgba(239, 68, 68, 0.1); color: var(--color-danger); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 1.25rem auto;">
          <i data-lucide="shield-alert" style="width: 28px; height: 28px;"></i>
        </div>
        <h2 style="margin: 0 0 0.5rem 0; font-size: 1.3rem; color: var(--text-primary);">${title}</h2>
        <p style="color: var(--text-secondary); font-size: 0.9rem; line-height: 1.5; margin-bottom: 1.5rem;">${message}</p>
        <a href="/" class="btn btn-secondary" style="display: inline-flex; align-items: center; gap: 0.5rem;">
          <i data-lucide="home"></i> Return to Homepage
        </a>
      </div>
    `;
    if (window.lucide) window.lucide.createIcons();
  },

  renderPortal(container, data) {
    const dataObj = data || {};
    const client = dataObj.client || { name: 'Client Profile', type: 'Individual' };
    const chambers = dataObj.chambers || { lawyerName: 'Adv. Vaibhav Sharma', firmName: 'VSH Legal Chambers' };
    const casesList = dataObj.cases || [];

    let casesHtml = '';
    if (casesList.length === 0) {
      casesHtml = `
        <div class="card" style="padding: 2.5rem; text-align: center;" class="text-muted">
          <i data-lucide="folder-open" style="width: 40px; height: 40px; margin-bottom: 0.5rem; opacity: 0.4;"></i>
          <p style="margin: 0; font-size: 0.9rem;">No active legal matters are currently listed under this portal.</p>
        </div>
      `;
    } else {
      casesHtml = casesList.map(cs => {
        const nextDateStr = cs.nextHearingDate 
          ? new Date(cs.nextHearingDate).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })
          : 'TBD / Pending Fixation';

        let hearingsHtml = '';
        if (cs.hearings && cs.hearings.length > 0) {
          hearingsHtml = `
            <div style="margin-top: 1.25rem; border-top: 1px solid var(--border-color); padding-top: 1rem;">
              <h4 style="font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-secondary); margin: 0 0 0.75rem 0;">Hearing Progress Logs</h4>
              <div style="display: flex; flex-direction: column; gap: 0.6rem;">
                ${cs.hearings.map(h => `
                  <div style="background: var(--bg-hover); border-radius: var(--radius-sm); padding: 0.6rem 0.8rem; font-size: 0.82rem;">
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.2rem;">
                      <strong style="color: var(--color-primary);">${h.date || 'Date N/A'}</strong>
                      <span class="badge" style="background: rgba(59, 130, 246, 0.12); color: #3b82f6; font-size: 0.7rem;">${h.stage || 'Hearing'}</span>
                    </div>
                    <p style="margin: 0; color: var(--text-primary); line-height: 1.3;">${h.notes || 'Hearing proceedings logged.'}</p>
                  </div>
                `).join('')}
              </div>
            </div>
          `;
        }

        return `
          <div class="card" style="margin-bottom: 1.5rem; padding: 1.5rem; border-left: 4px solid var(--color-primary);">
            <div style="display: flex; justify-content: space-between; align-items: flex-start; flex-wrap: wrap; gap: 0.75rem; margin-bottom: 1rem;">
              <div>
                <span class="badge badge-info" style="margin-bottom: 0.35rem; font-size: 0.7rem;">${cs.caseType}</span>
                <h3 style="margin: 0; font-size: 1.25rem; color: var(--text-primary); font-family: 'Playfair Display', serif;">${cs.title}</h3>
                <div style="font-size: 0.8rem; color: var(--text-secondary); margin-top: 0.2rem;">
                  <span>Ref / CNR: <strong>${cs.caseNumber}</strong></span> &bull; 
                  <span>Forum: <strong>${cs.court}</strong></span>
                </div>
              </div>
              <div>
                <span class="badge" style="background: rgba(16, 185, 129, 0.15); color: #10b981; font-weight: 700; font-size: 0.75rem; padding: 0.3rem 0.75rem; border-radius: 12px;">
                  ${cs.status}
                </span>
              </div>
            </div>

            <!-- Next Hearing Banner Callout -->
            <div style="background: linear-gradient(135deg, rgba(217, 119, 6, 0.08) 0%, rgba(16, 185, 129, 0.08) 100%); border: 1px solid rgba(217, 119, 6, 0.25); border-radius: var(--radius-md); padding: 1rem; text-align: center; margin-bottom: 1rem;">
              <span style="font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--text-secondary); display: block; margin-bottom: 0.25rem;">Next Hearing Schedule</span>
              <strong style="color: var(--color-primary); font-size: 1.2rem; display: block;">${nextDateStr}</strong>
              <span style="font-size: 0.8rem; color: var(--text-primary); margin-top: 0.25rem; display: inline-block;">Stage: <strong>${cs.stage}</strong></span>
            </div>

            ${hearingsHtml}
          </div>
        `;
      }).join('');
    }

    container.innerHTML = `
      <div style="max-width: 850px; margin: 0 auto; padding-bottom: 3rem;">
        
        <!-- Header Chambers Identity Banner -->
        <div class="card" style="background: linear-gradient(135deg, var(--bg-card) 0%, rgba(37, 99, 235, 0.05) 100%); border: 1px solid var(--border-color); margin-bottom: 1.5rem; padding: 1.5rem;">
          <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;">
            <div>
              <div style="font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: var(--color-primary); font-weight: 700; margin-bottom: 0.25rem;">CONFIDENTIAL CLIENT CASE TRACKER</div>
              <h1 style="margin: 0; font-size: 1.5rem; color: var(--text-primary); font-family: 'Playfair Display', serif;">${chambers.firmName}</h1>
              <div style="font-size: 0.85rem; color: var(--text-secondary); margin-top: 0.25rem;">
                Lead Counsel: <strong style="color: var(--text-primary);">${chambers.lawyerName}</strong>
              </div>
            </div>
            <div style="background: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3); padding: 0.5rem 1rem; border-radius: 20px; font-size: 0.8rem; color: #10b981; display: flex; align-items: center; gap: 0.4rem;">
              <i data-lucide="shield-check" style="width: 16px; height: 16px;"></i> Encrypted Direct Link
            </div>
          </div>
        </div>

        <!-- Client Dossier Greeting Card -->
        <div class="card" style="margin-bottom: 1.5rem; padding: 1.25rem; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 0.75rem;">
          <div style="display: flex; align-items: center; gap: 0.75rem;">
            <div style="width: 44px; height: 44px; border-radius: 50%; background: var(--color-primary); color: #fff; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 1.1rem;">
              ${client.name ? client.name.charAt(0).toUpperCase() : 'C'}
            </div>
            <div>
              <h3 style="margin: 0; font-size: 1.1rem; color: var(--text-primary);">${client.name}</h3>
              <span style="font-size: 0.78rem; color: var(--text-muted);">${client.type} Client Profile</span>
            </div>
          </div>
          <div style="font-size: 0.8rem; color: var(--text-secondary);">
            Active Matters: <strong style="color: var(--text-primary); font-size: 0.95rem;">${casesList.length} Case(s)</strong>
          </div>
        </div>

        <!-- Active Cases Feed -->
        ${casesHtml}

        <!-- Footer Contact Chambers CTA -->
        <div style="text-align: center; margin-top: 2rem; padding: 1.5rem; border-top: 1px dashed var(--border-color); font-size: 0.85rem; color: var(--text-secondary);">
          <p style="margin: 0 0 0.5rem 0;">Need clarification on your listed hearing dates or filings?</p>
          <strong style="color: var(--text-primary); display: block; font-size: 0.95rem;">${chambers.firmName} &bull; ${chambers.lawyerName}</strong>
        </div>

      </div>
    `;

    if (window.lucide) window.lucide.createIcons();
  }
};

export default portalModule;
